# styles

defaults = {
    "def_pre_text": "closeup image of a 21 year old",
    "def_post_text": "",
    "def_gender": "woman",
    "def_ethnicity": "* Europe * British",
    "def_shottype": "half-body shot",
    "def_haircolour": "Blonde colour",
    "def_hairstyle": "Random",
    "def_occasion": "Formal Gala",  # NEW default value for occasion
    "def_dressstyle": "Random",
    "def_dresscolour": "Random",
    "def_material": "Random",
    "def_pattern": "Random",
    "def_pre_textl": "plain gradient background",
    "def_post_textl": "",
    "def_adjective": "None",
    "def_landscape": "None",
    "def_lighting": "None",
    "def_mood": "None",
    "def_depthfocus": "None",
    "def_color_texture": "None",
    "def_style1": "Enhance",
    "def_style2": "Glamour",
    "def_style3": "sai-digital art"
}


styles_marc_k3nt3l = [
    'MK Chromolithography',
    'MK Cross Processing Print',
    'MK Dufaycolor Photograph',
    'MK Herbarium',
    'MK Punk Collage',
    'MK mosaic',
    'MK Van Gogh',
    'MK Coloring Book',
    'MK Singer Sargent',
    'MK Pollock',
    'MK Basquiat',
    'MK Andy Warhol',
    'MK Halftone print',
    'MK Gond Painting',
    'MK Albumen Print',
    'MK Aquatint Print',
    'MK Anthotype Print',
    'MK Inuit Carving',
    'MK Bromoil Print',
    'MK Calotype Print',
    'MK Color Sketchnote',
    'MK Cibulak Porcelain',
    'MK Alcohol Ink Art',
    'MK One Line Art',
    'MK Blacklight Paint',
    'MK Carnival Glass',
    'MK Cyanotype Print',
    'MK Cross-Stitching',
    'MK Encaustic Paint',
    'MK Embroidery',
    'MK Gyotaku',
    'MK Luminogram',
    'MK Lite Brite Art',
    'MK Mokume-gane',
    'Pebble Art',
    'MK Palekh',
    'MK Suminagashi',
    'MK Scrimshaw',
    'MK Shibori',
    'MK Vitreous Enamel',
    'MK Ukiyo-e',
    'MK vintage-airline-poster',
    'MK vintage-travel-poster',
    'MK bauhaus-style',
    'MK afrofuturism',
    'MK atompunk',
    'MK constructivism',
    'MK chicano-art',
    'MK de-stijl',
    'MK dayak-art',
    'MK fayum-portrait',
    'MK illuminated-manuscript',
    'MK kalighat-painting',
    'MK madhubani-painting',
    'MK pictorialism',
    'MK pichwai-painting',
    'MK patachitra-painting',
    'MK samoan-art-inspired',
    'MK tlingit-art',
    'MK adnate-style',
    'MK ron-english-style',
    'MK shepard-fairey-style'
]
styles_mre = [
    'mre-cinematic-dynamic',
    'mre-spontaneous-picture',
    'mre-artistic-vision',
    'mre-dark-dream',
    'mre-gloomy-art',
    'mre-bad-dream',
    'mre-underground',
    'mre-surreal-painting',
    'mre-dynamic-illustration',
    'mre-undead-art',
    'mre-elemental-art',
    'mre-space-art',
    'mre-ancient-illustration',
    'mre-brave-art',
    'mre-heroic-fantasy',
    'mre-dark-cyberpunk',
    'mre-lyrical-geometry',
    'mre-sumi-e-symbolic',
    'mre-sumi-e-detailed',
    'mre-manga',
    'mre-anime',
    'mre-comic'
]
styles_sai = [
    'sai-3d-model',
    'sai-analog film',
    'sai-anime',
    'sai-cinematic',
    'sai-comic book',
    'sai-craft clay',
    'sai-digital art',
    'sai-enhance',
    'sai-fantasy art',
    'sai-isometric',
    'sai-line art',
    'sai-lowpoly',
    'sai-neonpunk',
    'sai-origami',
    'sai-photographic',
    'sai-pixel art',
    'sai-texture'
]
styles_000 = [
    '000 Avant Garde Marcel Duchamp',
    '000 Avant Garde Aleksandra Ekster',
    '000 Avant Garde Natalia Goncharova',
    '000 Avant Garde Picasso',
    '000 Art Nouveau Egon Schiele',
    '000 Art Nouveau Toulouse Lautrec',
    '000 Art Nouveau Alphonse Mucha',
    '000 Art Nouveau Aubrey Beardsley',
    '000 Art Deco Jean Dunand',
    '000 Art Deco Le Corbusier',
    '000 Art Deco Charles-Édouard Jeanneret-Gris',
    '000 Art Deco Rene Lalique',
    '000 Abstract Expressionism Willem de Kooning',
    '000 Abstract Expressionism Lee Krasner',
    '000 Abstract Expressionism Jackson Pollock',
    '000 Abstract Expressionism Elaine de Kooning',
    '000 Baroque Peter Paul Rubens',
    '000 Baroque Caravaggio',
    '000 Baroque Diego Velazquez',
    '000 Baroque Rembrandt van Rijn',
    '000 Baroque Nicolas Poussin',
    '000 Baroque Mary Beale',
    '000 Classisicm Annibale Carracci',
    '000 Classisicm Claude Lorrain',
    '000 Classisicm Jacques-Louis David',
    '000 Classisicm Jean-Auguste Dominique Ingres',
    '000 Classisicm Anton Raphael Mengs',
    '000 Baroque Thomas Gainsborough',
    '000 Cubism Georges Braque',
    '000 Cubism Juan Gris',
    '000 Cubism Marie Laurencin',
    '000 Cubism Sonia Delaunay',
    '000 Dadaism Marcel Duchamp',
    '000 Dadaism Hans Arp',
    '000 Dadaism Hannah Hoech',
    '000 Dadaism Sophie Taeuber-Arp',
    '000 Expressionism Edvard Munch',
    '000 Expressionism Wassily Kandinsky',
    '000 Expressionism Gabriele Muenter',
    '000 Expressionism Kaethe Kollwitz',
    '000 Futurism Filippo Tommaso Marinetti',
    '000 Futurism Luigi Russolo',
    '000 Futurism Natalia Goncharova',
    '000 Futurism Benedetta Cappa Marinetti',
    '000 Gothic Art Giotto',
    '000 Gothic Art Duccio di Buoninsegna',
    '000 Gothic Art Cimabue',
    '000 Gothic Art Fra Angelico',
    'Photomaker Cinematic',
    'Photomaker Disney Character',
    'Photomaker Digitial Art',
    'Photomaker Photographic (Default)',
    'Photomaker Fantasy Art',
    'Photomaker Neonpunk',
    'Photomaker Enhance',
    'Photomaker Comic Book',
    'Photomaker Lowpoly',
    'Photomaker Lineart',
    '000 Sarah',
    '000 Sarah Studio',
    '000 SFW'
]

styles_diva = [
    'cinematic-diva',
    'Abstract Expressionism',
    'Academia',
    'Action Figure',
    'Adorable 3D Character',
    'Adorable Kawaii',
    'Art Deco',
    'Art Nouveau',
    'Astral Aura',
    'Avant-garde',
    'Baroque',
    'Bauhaus-Style Poster',
    'Blueprint Schematic Drawing',
    'Caricature',
    'Cel Shaded Art',
    'Character Design Sheet',
    'Classicism Art',
    'Color Field Painting',
    'Colored Pencil Art',
    'Conceptual Art',
    'Constructivism',
    'Cubism',
    'Dadaism',
    'Dark Fantasy',
    'Dark Moody Atmosphere',
    'DMT Art Style',
    'Doodle Art',
    'Double Exposure',
    'Dripping Paint Splatter Art',
    'Expressionism',
    'Faded Polaroid Photo',
    'Fauvism',
    'Flat 2D Art',
    'Fortnite Art Style',
    'Futurism',
    'Glitchcore',
    'Glo-fi',
    'Googie Art Style',
    'Graffiti Art',
    'Harlem Renaissance Art',
    'High Fashion',
    'Idyllic',
    'Impressionism',
    'Infographic Drawing',
    'Ink Dripping Drawing',
    'Japanese Ink Drawing',
    'Knolling Photography',
    'Light Cheery Atmosphere',
    'Logo Design',
    'Luxurious Elegance',
    'Macro Photography',
    'Mandola Art',
    'Marker Drawing',
    'Medievalism',
    'Minimalism',
    'Neo-Baroque',
    'Neo-Byzantine',
    'Neo-Futurism',
    'Neo-Impressionism',
    'Neo-Rococo',
    'Neoclassicism',
    'Op Art',
    'Ornate and Intricate',
    'Pencil Sketch Drawing',
    'Pop Art 2',
    'Rococo',
    'Silhouette Art',
    'Simple Vector Art',
    'Sketchup',
    'Steampunk 2',
    'Surrealism',
    'Suprematism',
    'Terragen',
    'Tranquil Relaxing Atmosphere',
    'Sticker Designs',
    'Vibrant Rim Light',
    'Volumetric Lighting',
    'Watercolor 2',
    'Whimsical and Playful'
]

styles_twri = [
    'ads-advertising',
    'ads-automotive',
    'ads-corporate',
    'ads-fashion editorial',
    'ads-food photography',
    'ads-gourmet food photography',
    'ads-luxury',
    'ads-real estate',
    'ads-retail',
    'artstyle-abstract',
    'artstyle-abstract expressionism',
    'artstyle-art deco',
    'artstyle-art nouveau',
    'artstyle-constructivist',
    'artstyle-cubist',
    'artstyle-expressionist',
    'artstyle-graffiti',
    'artstyle-hyperrealism',
    'artstyle-impressionist',
    'artstyle-pointillism',
    'artstyle-pop art',
    'artstyle-psychedelic',
    'artstyle-renaissance',
    'artstyle-steampunk',
    'artstyle-surrealist',
    'artstyle-typography',
    'artstyle-watercolor',
    'futuristic-biomechanical',
    'futuristic-biomechanical cyberpunk',
    'futuristic-cybernetic',
    'futuristic-cybernetic robot',
    'futuristic-cyberpunk cityscape',
    'futuristic-futuristic',
    'futuristic-retro cyberpunk',
    'futuristic-retro futurism',
    'futuristic-sci-fi',
    'futuristic-vaporwave',
    'game-bubble bobble',
    'game-cyberpunk game',
    'game-fighting game',
    'game-gta',
    'game-mario',
    'game-minecraft',
    'game-pokemon',
    'game-retro arcade',
    'game-retro game',
    'game-rpg fantasy game',
    'game-strategy game',
    'game-streetfighter',
    'game-zelda',
    'misc-architectural',
    'misc-disco',
    'misc-dreamscape',
    'misc-dystopian',
    'misc-fairy tale',
    'misc-gothic',
    'misc-grunge',
    'misc-horror',
    'misc-kawaii',
    'misc-lovecraftian',
    'misc-macabre',
    'misc-manga',
    'misc-metropolis',
    'misc-minimalist',
    'misc-monochrome',
    'misc-nautical',
    'misc-space',
    'misc-stained glass',
    'misc-techwear fashion',
    'misc-tribal',
    'misc-zentangle',
    'papercraft-collage',
    'papercraft-flat papercut',
    'papercraft-kirigami',
    'papercraft-paper mache',
    'papercraft-paper quilling',
    'papercraft-papercut collage',
    'papercraft-papercut shadow box',
    'papercraft-stacked papercut',
    'papercraft-thick layered papercut',
    'photo-alien',
    'photo-film noir',
    'photo-glamour',
    'photo-hdr',
    'photo-iphone photographic',
    'photo-long exposure',
    'photo-neon noir',
    'photo-silhouette',
    'photo-tilt-shift'
]

styles_main = [
    'base', '3D Model', 'Abstract', 'Abstract Expressionism', 'Abstract Expressionism 2',
    'Academia', 'Action Figure', 'Adorable 3D Character', 'Adorable Kawaii', 'Advertising',
    'Alien', 'Analog Film', 'Anime', 'Architectural', 'Art Deco', 'Art Deco 2',
    'Art Nouveau', 'Art Nouveau 2', 'Astral Aura', 'Avant-garde', 'Baroque',
    'Bauhaus-Style Poster', 'Biomechanical', 'Biomechanical Cyberpunk', 'Blueprint Schematic Drawing',
    'Bubble Bobble Game', 'Caricature', 'Cel Shaded Art', 'Character Design Sheet', 'Cinematic Film',
    'Cinematic Photograph', 'Classicism Art', 'Collage', 'Color Field Painting', 'Colored Pencil Art',
    'Commercial Illustration 1920s', 'Comic Book', 'Conceptual Art', 'Constructivism 1', 'Constructivism 2',
    'Craft Clay', 'Cubism 1', 'Cubism 2', 'Cybernetic', 'Cybernetic Robot', 'Cyberpunk Cityscape',
    'Cyberpunk', 'DMT Art Style', 'Dadaism', 'Dark Fantasy', 'Dark Moody Atmosphere', 'Digital Art',
    'Disco', 'Doodle Art', 'Double Exposure', 'Dreamscape', 'Dripping Paint Splatter Art', 'Dystopian',
    'Enhance', 'Expressionism 1', 'Expressionism 2', 'Faded Polaroid Photo', 'Fairy Tale', 'Fantasy Art',
    'Fauvism', 'Fighting Game', 'Film Noir', 'Flat 2D Art', 'Flat Papercut', 'Food Photography',
    'Fortnite Art Style', 'Futurism', 'Futuristic', 'Futuristic Sci-Fi', 'GTA', 'Glamour',
    'Glitchcore', 'Glo-fi', 'Googie Art Style', 'Gothic', 'Graffiti Art 1', 'Graffiti Art 2',
    'Grunge', 'HDR', 'Harlem Renaissance Art', 'High Fashion', 'Horror', 'Hyperrealism',
    'Idyllic', 'Impressionism 1', 'Impressionism 2', 'Infographic Drawing', 'Ink Dripping Drawing', 'Isometric Style',
    'Japanese Ink Drawing', 'Kawaii', 'Kirigami', 'Knolling Photography', 'Legend of Zelda', 'Light Cheery Atmosphere',
    'Line Art', 'Logo Design', 'Long Exposure', 'Lovecraftian Horror', 'Lowpoly', 'Luxurious Elegance',
    'Macabre', 'Macro Photography', 'Mandala Art', 'Manga', 'Marker Drawing', 'Medievalism',
    'Metropolis', 'Minecraft', 'Minimalism 1', 'Minimalism 2', 'Monochrome', 'Nautical',
    'Neo-Baroque', 'Neo-Byzantine', 'Neo-Futurism', 'Neo-Impressionism', 'Neo-Rococo', 'Neoclassicism',
    'Neon Noir', 'Neon Punk', 'Op Art', 'Origami', 'Ornate and Intricate', 'Paper Mache',
    'Paper Quilling', 'Papercut Collage', 'Papercut Shadow Box', 'Pencil Sketch', 'Photographic', 'Pixel Art',
    'Pointillism', 'Pokémon', 'Pop Art 1', 'Pop Art 2', 'Psychedelic', 'RPG Fantasy',
    'Real Estate Photography', 'Renaissance', 'Retro Arcade', 'Retro Game', 'Retro Cyberpunk', 'Retro Futurism',
    'Retro game', 'Rococo', 'Silhouette', 'Silhouette Art', 'Simple Vector Art', 'Sketchup',
    'Space', 'Stacked Papercut', 'Stained Glass', 'Steampunk 1', 'Steampunk 2', 'Sticker Designs',
    'Strategy Game', 'Street Fighter', 'Super Mario', 'Suprematism', 'Surrealism 1', 'Surrealism 2',
    'Techwear Fashion', 'Terragen', 'Texture', 'Thick Layered Papercut', 'Tilt-Shift Photo', 'Tranquil Relaxing Atmosphere',
    'Tribal', 'Typography', 'Vaporwave', 'Vibrant Rim Light', 'Volumetric Lighting', 'Watercolor 1',
    'Watercolor 2', 'Whimsical and Playful', 'Wild West', 'Zentangle', 'ads-advertising', 'ads-automotive',
    'ads-corporate', 'ads-fashion editorial', 'ads-food photography', 'ads-gourmet food photography', 'ads-luxury', 'ads-real estate',
    'ads-retail'
]


color_textures = sorted([
    "Simple, Plain, Minimal details, Uniform background",
    "Sparse, Basic, Few details, Straightforward background",
    "Clean, Neat, Moderate details, Organized background",
    "Balanced, Orderly, Balanced details, Structured background",
    "Average, Decent, Standard details, Typical background",
    "Elaborate, Engaging, Abundant details, Engaging background",
    "Rich, Intricate, Detailed elements, Rich background",
    "Complex, Varied, Diverse details, Intricate background",
    "Exquisite, Ornate, Elaborate details, Ornate background",
    "Intricate, Detailed, Highly detailed scene, Intricate background"
])

depthfocus_list = sorted([
    "background blurred",
    "background slightly blurred",
    "background sharp",
    "softly focused background",
    "bokeh background"
])

moods = sorted([
    "Tranquil",
    "Vibrant",
    "Mysterious",
    "Serene",
    "Melancholic",
    "Energetic",
    "Dramatic",
    "Dreamy",
    "Peaceful",
    "Chaotic",
    "Romantic",
    "Surreal",
    "Nostalgic",
    "Foreboding",
    "Joyful"
])

lightings = sorted([
    "Clear night with starry skies and moonlight",
    "Cloudy day with warm sunlight",
    "Cloudy day with warm sunlight reflecting off water",
    "Foggy night with eerie moonlight",
    "Foggy night with moonlit silhouettes",
    "Misty day with glowing light",
    "Misty day with glowing light during sunrise",
    "Overcast day with dimmed sunlight",
    "Overcast day with gentle diffused light",
    "Overcast day with soft, ethereal light",
    "Overcast day with foggy conditions",
    "Rainy day with misty light",
    "Overcast day with sleet",
    "Snowy day with sparkling light on fresh snow",
    "Sunny day with clear blue skies",
    "Sunny day with soft sunlight",
    "Sunny day with soft sunlight filtering through clouds",
    "Sunny day with vibrant sunlight",
    "Sunny day with warm golden light",
    "Sunset with golden hour light",
    "Sunrise with clear sky",
])


adjectives = sorted([
    "Majestic",
    "Spectacular",
    "Serene",
    "Breathtaking",
    "Picturesque",
    "Tranquil",
    "Scenic",
    "Idyllic",
    "Untouched",
    "Pristine",
    "Vibrant",
    "Lush",
    "Barren",
    "Dramatic",
    "Mystical",
    "Rugged",
    "Enchanting",
    "Surreal",
    "Awe-inspiring",
    "Ethereal"
])



landscapes = [
    # Outdoor Locations
    "Mountains", "Valleys", "Plateaus", "Plains", "Deserts", "Canyons", "Glaciers", "Tundras",
    "Forests", "Rainforests", "Swamps", "Marshes", "Grasslands", "Savannas", "Taigas", "Tropical islands",
    "Archipelagos", "Cliffs", "Caves", "Volcanoes", "Lakes", "Rivers", "Waterfalls", "Oceans",
    "Seas", "Bays", "Fjords", "Coral reefs", "Icebergs", "Sand dunes", "City skyline", "Urban park",
    "Botanical garden", "Amusement park", "Bridge", "Highway interchange", "Train station", "Airport",
    "Residential neighborhood", "Sports stadium", "Historical landmark", "Cemetery", "Seaport", "Harbor",
    "Dam", "Canal", "Aqueduct", "Wind farm", "Solar farm", "Spaceport", "Rooftop garden", "Urban alley with graffiti",
    "Street market", "Fountain in a public square", "Rustic barn", "Farm with rolling fields", "Orchard in bloom",
    "Vineyard with grapevines", "Castle ruins", "Medieval fortress", "Hot air balloon basket",
    "Carousel in a fairground",
    "Snow-covered forest", "Cherry blossom park", "Lavender field", "Tulip field", "Pumpkin patch", "Christmas market",
    "Ice rink", "Mountain cabin", "Ski resort", "Horse stable", "Wildflower meadow", "Sunset beach with dunes",
    "Desert oasis with palm trees",

    # Indoor Locations
    "Zoo", "Skyscraper", "Shopping mall", "Office complex", "Industrial area", "Convention center",
    "Theme park", "Oil refinery", "Power plant", "Living room with a fireplace", "Kitchen with a breakfast bar",
    "Bedroom with a cozy bed", "Home office with a desk and bookshelves", "Bathroom with a bathtub",
    "Dining room with a chandelier", "Library with floor-to-ceiling shelves", "Art studio with easels and paints",
    "Music room with instruments", "Gym with exercise equipment", "Home theater with plush seating",
    "Wine cellar with wine racks", "Game room with a pool table", "Sunroom with indoor plants",
    "Conservatory with a grand piano", "Attic with vintage furniture", "Basement lounge with a bar",
    "Children's playroom with toys", "Craft room with sewing machine", "Laundry room with washing machine",
    "Mudroom with storage cubbies", "Walk-in closet with shelves and mirrors", "Pantry with shelves stocked with food",
    "Garage with tools and workbench", "Studio apartment with minimalist decor", "Loft with exposed brick walls",
    "Apartment balcony with city views", "Hotel lobby with luxurious furnishings", "Restaurant with elegant decor",
    "Café with cozy seating", "Bookstore with reading nooks", "Art gallery with white walls and spotlights",
    "Museum exhibit with artifacts", "Theater stage with velvet curtains", "Recording studio with soundproofing",
    "University lecture hall with rows of seats", "Hospital room with medical equipment",
    "Classroom with chalkboard and desks",
    "Conference room with a long table", "Hotel room with a king-size bed", "Spa with massage tables and candles",
    "Beauty salon with hair styling stations", "Tattoo parlor with art-covered walls",
    "Photography studio with backdrop and lights",
    "Dance studio with mirrored walls", "Yoga studio with mats and meditation area", "Indoor pool with lounge chairs",
    "Bowling alley with polished lanes", "Abandoned warehouse", "Old library with antique books",
    "Underwater in a swimming pool"
]

models = [
    'devlishphotorealism_sdxl15.safetensors',
    'babesBYSTABLEYOGI_xlV1.safetensors',
    'sdxlUnstableDiffusers_v8HEAVENSWRATH.safetensors',
    'lovexlAllInOneMega_v20.safetensors',
    'juggernautXL_v9Rdphoto2Lightning.safetensors',
    'dreamshaperXL_v21TurboDPMSDE.safetensors',
    'devlish LoveXL 050.safetensors',
    'sdxlUnstableDiffusers_v11.safetensors',
    'DEVLISH LIGHTNING.safetensors',
    'sdxlUnstableDiffusers_nihilmania.safetensors',
    'realvisxlV40_v40Bakedvae.safetensors',
    'realvisxlV40_v40LightningBakedvae.safetensors',
    'realvisxlV50_v50LightningBakedvae.safetensors',
    'juggernautXL_v8Rundiffusion.safetensors',
    'amuz_v30.safetensors',
    'CHEYENNE_v16.safetensors',
    'CHEYENNE_v18.safetensors',
    'devlish loveXL 050.safetensors',
    'loveXL Lightning.safetensors',
    'Cheyenne Devlish Amuz.safetensors',
    'Demon41_Midguardbeast.safetensors',
    'halcyonSDXL_v17.safetensors'
]

presets = [
    "LIGHT - SD1.5 only (low strength)",
    "STANDARD (medium strength)",
    "VIT-G (medium strength)",
    "PLUS (high strength)",
    "PLUS FACE (portraits)",
    "FULL FACE - SD1.5 only (portraits stronger)"
]

aspectratios = [
    "9:21 640x1536  (0.42)",
    "9:19 704x1472  (0.48)",
    "9:16 768x1344  (0.57)",
    "5:8  768x1216  (0.63)",
    "2:3  832x1216  (0.68)",
    "3:4  896x1152  (0.78)",
    "1:1  1024x1024 (1.00)",
    "4:3  1152x896  (1.29)",
    "3:2  1216x832  (1.46)",
    "8:5  1216x768  (1.58)",
    "16:9 1344x768  (1.75)",
    "19:9 1472x704  (2.09)",
    "21:9 1536x640  (2.40)"
]

oc_aspectratios = [
    "9:21 640x1536 (0.42)",
    "9:19 704x1472 (0.48)",
    "9:16 768x1344 (0.57)",
    "5:8 768x1216 (0.63)",
    "2:3 832x1216 (0.68)",
    "3:4 896x1152 (0.78)",
    "1:1 1024x1024 (1.00)",
    "4:3 1152x896 (1.29)",
    "3:2 1216x832 (1.46)",
    "8:5 1216x768 (1.58)",
    "16:9 1344x768 (1.75)",
    "19:9 1472x704 (2.09)",
    "21:9 1536x640 (2.40)",
    "unchanged"
]

killworkflow_choices = ["Yes", "No"]

model_parameters = """0,devlishphotorealism_sdxl15.safetensors,30,4.0,dpmpp_2m_sde,karras
1,sdxlUnstableDiffusers_v8HEAVENSWRATH.safetensors,30,4.0,dpmpp_2m_sde,karras
2,lovexlAllInOneMega_v20.safetensors,30,4.0,dpmpp_2m_sde,karras
3,juggernautXL_v9Rdphoto2Lightning.safetensors,5,1.5,dpmpp_sde,karras
4,dreamshaperXL_v21TurboDPMSDE.safetensors,6,2.0,dpmpp_sde,karras
5,devlish LoveXL 050.safetensors,30,4.0,dpmpp_2m_sde,karras
6,sdxlUnstableDiffusers_v11.safetensors,30,4.0,dpmpp_2m_sde,karras
7,DEVLISH LIGHTNING.safetensors,5,1.5,dpmpp_sde,karras
8,sdxlUnstableDiffusers_nihilmania.safetensors,30,4.0,dpmpp_2m_sde,karras
9,realvisxlV40_v40Bakedvae.safetensors,30,4.0,dpmpp_2m,karras
10,realvisxlV40_v40LightningBakedvae.safetensors,12,1,ddpm,sgm_uniform
11,realvisxlV50_v50LightningBakedvae.safetensors,12,1,ddpm,sgm_uniform
12,juggernautXL_v8Rundiffusion.safetensors,30,4.0,dpmpp_2m,karras
13,amuz_v30.safetensors,30,4.0,dpmpp_2m_sde_gpu,karras
14,CHEYENNE_v16.safetensors,30,4.0,dpmpp_2m_sde_gpu,karras
15,CHEYENNE_v18.safetensors,30,4.0,dpmpp_2m_sde_gpu,karras
16,devlish loveXL 050.safetensors,30,4.0,dpmpp_2m_sde_gpu,karras
17,loveXL Lightning.safetensors,8,1.5,dpmpp_sde,karras
18,Cheyenne Devlish Amuz.safetensors,30,4.0,dpmpp_2m_sde_gpu,karras
19,Demon41_Midguardbeast.safetensors,20,2.5,euler,normal
20,halcyonSDXL_v17.safetensors,30,5,dpmpp_3m_sde,karras
21,babesBYSTABLEYOGI_xlV1.safetensors, 30,5,dpmpp_3m_sde,karras 
"""

colors_list = [
    "Red Rubiate (0)",
    "Husky Orange (15)",
    "Beeswax Candle Orange (30)",
    "Tiki Torch Yellow (45)",
    "Tropic Canary Yellow (60)",
    "Green Caterpillar (75)",
    "Hill Lands Green (90)",
    "Skirret Green (105)",
    "Grass Green (120)",
    "Artificial Turf (135)",
    "Esmeralda Green (150)",
    "Macau Green (165)",
    "Montego Bay Blue (180)",
    "Fairy Tale Blue (195)",
    "Tufts Blue (210)",
    "Free Speech Blue (225)",
    "Early Spring Night Blue (240)",
    "Dragonlord Purple (255)",
    "Purple Rain (270)",
    "Akebi Purple (285)",
    "Ultraviolet Cryner (300)",
    "Boat Orchid Pink (315)",
    "Razzle Dazzle (330)",
    "Saffron Desires (345)"
]

blend_modes = [
    'normal',
    'dissolve',
    'darken',
    'multiply',
    'color burn',
    'linear burn',
    'darker color',
    'lighten',
    'screen',
    'color dodge',
    'linear dodge (add)',
    'lighter color',
    'overlay',
    'soft light',
    'hard light',
    'vivid light',
    'linear light',
    'pin light',
    'hard mix',
    'difference',
    'exclusion',
    'subtract',
    'divide',
    'hue',
    'saturation',
    'color',
    'luminosity',
    'grain extract',
    'grain merge'
]

blend_modes_large = [
    "normal", "dissolve", "darken", "multiply", "color burn", "linear burn", "darker color",
    "lighten", "screen", "color dodge", "linear dodge (add)", "lighter color", "overlay",
    "soft light", "hard light", "vivid light", "linear light", "pin light", "hard mix",
    "difference", "exclusion", "subtract", "divide", "hue", "saturation", "color",
    "luminosity", "grain extract", "grain merge"
]

blend_modes_short = [
    "normal", "multiply", "screen", "overlay", "soft_light"
]

preprocessor_list = [
    "None",
    "tile",
    "canny",
    "lineart",
    "lineart_coarse",
    "lineart_anime",
    "lineart_manga",
    "scribble",
    "scribble_hed",
    "hed",
    "hed_safe",
    "pidi",
    "pidi_safe",
    "mlsd",
    "openpose",
    "pose",
    "dwpose",
    "normalmap_bae",
    "normalmap_midas",
    "depth_midas",
    "depth",
    "depth_zoe",
    "seg_ofcoco",
    "seg_ofade20k",
    "seg_ufade20k",
    "tile"
]

save_format = ["webp", "jpeg", "png"]

controlnet_list = [
    'Depth-anything_controlnet.safetensors',
    'OpenPoseXL2.safetensors',
    'control_openpose-fp16.safetensors',
    'control_sdi5_inpaint_depth_hand_fp16.safetensors',
    'control_sdi5_random_color.pth',
    'control_vile_sdi5_ip2p.pth',
    'control_vile_sdi5_shuffle.pth',
    'control_viifle_sdi5_tile.pth',
    'control_viifip_sdi5_depth.pth',
    'control_viip_sdi5_canny.pth',
    'control_viip_sdi5_inpaint.pth',
    'control_viip_sdi5_lineart.pth',
    'control_viip_sdi5_mlsd.pth',
    'control_viip_sdi5_normalbae.pth',
    'control_viip_sdi5_openpose.pth',
    'control_viip_sdi5_scribble.pth',
    'control_viip_sdi5_seg.pth',
    'control_viip_sdi5_softedge.pth',
    'control_viip_sdi5s2_lineart_anime.pth',
    'controlnet-union-sdxl.safetensors',
    'controlnet-union-sdxl_promax.safetensors',
    'depth-anything-large.safetensors',
    'diffusers_»|_canny_mid.safetensors',
    'diffusers_»|_depth_mid.safetensors',
    'diffusion_pytorch_model.safetensors',
    'instantid\\diffusion_pytorch_model.safetensors',
    'ioclab_sd15_recolor.safetensors',
    'lightingBasedPicture_v10.safetensors',
    'sai_xl_recolor_256lora.safetensors',
    'sai_xl_sketch_256lora.safetensors',
    't2i-adapter-lineart-sdxl-1.0.safetensors',
    't2i-adapter_x|_openpose.safetensors',
    't2i_adapter_openpose_sdxl.safetensors',
    't2iadapter_color_sdi4vi.pth',
    't2iadapter_style_sd14v1.pth',
    'thibaud_x|_openpose.safetensors',
    'thibaud_x|_openpose_256lora.safetensors',
    'ttplanetSDXLContralnet_v10Fp16.safetensors'
]

preprocessor_list2 = [
    "none",
    "AnimeFace_SemSegPreprocessor",
    "AnyLineArtPreprocessor_aux",
    "BinaryPreprocessor",
    "CannyEdgePreprocessor",
#    "ColorPreprocessor",
    "DensePosePreprocessor",
    "DepthAnythingPreprocessor",
    "Zoe_DepthAnythingPreprocessor",
    "DepthAnythingV2Preprocessor",
    "DSINE-NormalMapPreprocessor",
#    "DWPreprocessor",
#    "AnimalPosePreprocessor",
    "HEDPreprocessor",
    "FakeScribblePreprocessor",
    "LeReS-DepthMapPreprocessor",
    "LineArtPreprocessor",
    "AnimeLineArtPreprocessor",
    "LineartStandardPreprocessor",
    "Manga2Anime_LineArt_Preprocessor",
    "MediaPipe-FaceMeshPreprocessor",
#    "MeshGraphormer-DepthMapPreprocessor",
    "Metric3D-DepthMapPreprocessor",
    "Metric3D-NormalMapPreprocessor",
    "MiDaS-NormalMapPreprocessor",
    "MiDaS-DepthMapPreprocessor",
#    "M-LSDPreprocessor",
    "BAE-NormalMapPreprocessor",
    "OneFormer-COCO-SemSegPreprocessor",
    "OneFormer-ADE20K-SemSegPreprocessor",
#    "OpenposePreprocessor",
    "PiDiNetPreprocessor",
    "ImageLuminanceDetector",
    "ImageIntensityDetector",
    "ScribblePreprocessor",
    "Scribble_XDoG_Preprocessor",
    "Scribble_PiDiNet_Preprocessor",
    "SAMPreprocessor",
#    "ShufflePreprocessor",
    "TEEDPreprocessor",
    "TilePreprocessor",
    "TTPlanet_TileGF_Preprocessor",
    "TTPlanet_TileSimple_Preprocessor",
    "UniFormer-SemSegPreprocessor",
    "SemSegPreprocessor",
    "Zoe-DepthMapPreprocessor"
]

genders = ["woman", "man", "female man", "male woman"]

shottypes = ["Random", "None"] + ([
    "close-up", "half-body shot", "full-body shot"
])

ethnicities = ["Random", "None"] + [
    "* North America * American",
    "* North America * Canadian",
    "* North America * Mexican",
    "* South America * Brazilian",
    "* South America * Argentinian",
    "* South America * Chilean",
    "* South America * Colombian",
    "* South America * Peruvian",
    "* Europe * British",
    "* Europe * English",
    "* Europe * Scottish",
    "* Europe * Welsh",
    "* Europe * French",
    "* Europe * German",
    "* Europe * Italian",
    "* Europe * Spanish",
    "* Europe * Portuguese",
    "* Europe * Dutch",
    "* Europe * Irish",
    "* Europe * Swedish",
    "* Europe * Norwegian",
    "* Europe * Swiss",
    "* Europe * Danish",
    "* Europe * Greek",
    "* Europe * Turkish",
    "* Europe * Belgian",
    "* Europe * Austrian",
    "* Europe * Polish",
    "* Europe * Finnish",
    "* Europe * Czech",
    "* Europe * Hungarian",
    "* Europe * Ukrainian",
    "* Europe * Romanian",
    "* Middle East * Israeli",
    "* Middle East * Saudi Arabian",
    "* Middle East * Emirati",
    "* Middle East * Iranian",
    "* Middle East * Iraqi",
    "* Middle East * Jordanian",
    "* Middle East * Lebanese",
    "* Middle East * Syrian",
    "* Africa * South African",
    "* Africa * Egyptian",
    "* Africa * Moroccan",
    "* Africa * Algerian",
    "* Africa * Ethiopian",
    "* Africa * Ghanaian",
    "* Africa * Kenyan",
    "* Africa * Malian",
    "* Africa * Senegalese",
    "* Africa * Somali",
    "* Africa * Tunisian",
    "* Asia * Japanese",
    "* Asia * Chinese",
    "* Asia * Indian",
    "* Asia * Korean",
    "* Asia * Thai",
    "* Asia * Vietnamese",
    "* Asia * Filipino",
    "* Asia * Indonesian",
    "* Asia * Malaysian",
    "* Asia * Singaporean",
    "* Asia * Afghan",
    "* Asia * Bangladeshi",
    "* Asia * Pakistani",
    "* Asia * Nepalese",
    "* Asia * Sri Lankan",
    "* Oceania * Australian",
    "* Oceania * New Zealander",
    "* Eastern Europe & Central Asia * Russian",
    "* Caribbean * Jamaican"
]

haircolours = ["Random", "None"] + [
    "Black colour",
    "Jet Black colour",
    "Brown colour",
    "Brunette colour",
    "Dark Brown colour",
    "Light Brown colour",
    "Chestnut colour",
    "Mahogany colour",
    "Caramel colour",
    "Honey colour",
    "Blonde colour",
    "Platinum Blonde colour",
    "Ash Blonde colour",
    "Dirty Blonde colour",
    "Golden Blonde colour",
    "Sandy Blonde colour",
    "Red colour",
    "Auburn colour",
    "Burgundy colour",
    "Copper colour",
    "Strawberry Blonde colour",
    "Blue colour",
    "Green colour",
    "Purple colour",
    "Pink colour",
    "Turquoise colour",
    "Lavender colour",
    "Neon Green colour",
    "Silver colour",
    "Rose Gold colour",
    "Silver colour",
    "White colour",
    "Grey colour"
]

hairstyles = ["Random", "None"] + [
    "Blunt bob hairstyle",
    "Pixie cut hairstyle",
    "Wavy lob hairstyle",
    "Bob hairstyle",
    "Curly bob hairstyle",
    "Long bob hairstyle",
    "Sleek straight hairstyle",
    "Long layers hairstyle",
    "Curtain bangs hairstyle",
    "Beach waves hairstyle",
    "High ponytail hairstyle",
    "Messy bun hairstyle",
    "Chignon hairstyle",
    "Half-up half-down hairstyle",
    "Layered shoulder-length hairstyle",
    "Modern shag hairstyle",
]

hairstyles_old = ["Random", "None"] + [
    "Blunt bob hairstyle",
    "Egyptian bob hairstyle",
    "Pixie cut hairstyle",
    "Asymmetrical pixie hairstyle",
    "Buzz cut hairstyle",
    "Mohawk hairstyle",
    "Wavy lob hairstyle",
    "Shaggy layers hairstyle",
    "Layered shag hairstyle",
    "Feathered layers hairstyle",
    "Curly bob hairstyle",
    "Short natural curls hairstyle",
    "Long bob hairstyle",
    "Sleek straight hairstyle",
    "Long layers hairstyle",
    "Curtain bangs hairstyle",
    "Side swept bangs hairstyle",
    "Lob with side part hairstyle",
    "Balayage hairstyle",
    "Ombre hairstyle",
    "Beach waves hairstyle",
    "Shaggy bob hairstyle",
    "Medium length curls hairstyle",
    "High ponytail hairstyle",
    "Bubble ponytail hairstyle",
    "Sleek low ponytail hairstyle",
    "Blunt cut long hairstyle",
    "Long hair with bangs hairstyle",
    "Long wavy layers hairstyle",
    "Loose curls hairstyle",
    "Messy bun hairstyle",
    "Top knot hairstyle",
    "Chignon hairstyle",
    "Space buns hairstyle",
    "Sleek bun hairstyle",
    "Braided bun hairstyle",
    "Dutch braids hairstyle",
    "Fishtail braid hairstyle",
    "Cornrows hairstyle",
    "Braided crown hairstyle",
    "French braid hairstyle",
    "Waterfall braid hairstyle",
    "Half-up half-down hairstyle",
    "Half-up bun hairstyle",
    "Twisted half-up hairstyle",
    "Slicked back hairstyle",
    "Wet look hairstyle",
    "Gelled spikes hairstyle",
    "Victory rolls hairstyle",
    "Beehive hairstyle",
    "Finger waves hairstyle",
    "French twist hairstyle",
    "Updo with curls hairstyle",
    "Sleek chignon hairstyle",
    "Classic ponytail",
    "Side ponytail",
    "Braided ponytail",
    "Wrapped ponytail",
    "Twisted ponytail",
    "Messy ponytail",
    "Half-up ponytail",
    "Double ponytail",
    "Ponytail with bangs",
    "Curly ponytail",
    "Sleek ponytail",
    "Ponytail with accessories"
]
close_up_dress_styles = [
    "Random",
    "None",
    "Everyday crew-neck tee with a relaxed cotton finish",
    "Trendy cropped top with a slight scoop neckline and puff sleeves",
    "Structured blouse with a subtle V-neck and cap sleeves",
    "Crisp button-up shirt featuring a mandarin collar and rolled sleeves",
    "Off-shoulder blouse with delicate ruffle details",
    "Lightweight sleeveless tank with a soft racerback design",
    "Sporty mesh tank with a modern cut and minimal seams",
    "Sequin-embellished camisole with a gentle V-neck",
    "Soft ruffled blouse with a delicate lace trim",
    "Intricate lace top with fine detailing",
    "Fitted graphic tee with a subtle distressed finish",
    "Sleek off-shoulder crop top with a contoured silhouette",
    "Elegant satin blouse with a soft drape and sheen",
    "Cozy turtleneck sweater with refined ribbing",
    "Basic tee layered under a cropped denim jacket",
    "Bright halter-neck sundress in light, airy fabric",
    "Performance tee with a racerback and streamlined fit",
    "Fitted peplum top with a gentle sweetheart neckline",
    "Luxurious velvet blouse with a deep V-neck and cap sleeves",
    "Crisp polo-style knit top with a tailored collar",
    "Bohemian fringe top with subtle embroidered accents",
    "Relaxed knit sweater with an oversized, soft finish",
    "Off-shoulder crop top adorned with playful ruffles",
    "Tailored shirt dress with a modest collar and cuffed sleeves",
    "Minimalistic tube top with a smooth, clean design",
    "Asymmetric blouse with a one-shoulder design and soft drape",
    "Elegant wrap-style blouse featuring a deep V-neck",
    "Retro halter-neck top with bold prints and short sleeves",
    "Bold graphic tee with a relaxed, modern silhouette",
    "Delicate lace blouse with a high neck and scalloped trim",
    "Statement knit top with exaggerated sleeves and pattern",
    "Flowy peasant blouse with gentle embroidered details",
    "Ruffled off-shoulder top with soft draping",
    "Smooth silk blouse with a minimalist collar and sheen",
    "Breathable mesh top with a sporty, streamlined cut",
    "Breezy peplum top with subtle ruffle accents",
    "Light knit sweater with a classic crew neck and relaxed fit",
    "Sleek bodysuit with a high neckline and minimal straps",
    # New swimwear and underwear outfits:
    "Vibrant bikini top with tropical print and adjustable straps",
    "Chic one-piece swimsuit with a plunging neckline and side cutouts",
    "Delicate lace bralette with intricate embroidery",
    "Seamless cotton camisole with a soft, barely-there feel"
]


half_body_dress_styles = [
    "Random",
    "None",
    "Crew-neck tee + Classic fitted denim jeans",
    "Cropped top + High-waisted distressed shorts",
    "Structured blouse + Tailored pencil skirt",
    "Button-up shirt + High-waisted tapered trousers",
    "Off-shoulder blouse + Flowing midi skirt",
    "Tank top + High-rise denim shorts",
    "Mesh tank + Sleek athletic leggings",
    "Sequin camisole + Black slim trousers",
    "Ruffled blouse + A-line floral skirt",
    "Lace top + Flowy maxi skirt",
    "Graphic tee + Faux leather mini skirt",
    "Off-shoulder crop top + High-waisted mini skirt",
    "Satin blouse + Tailored straight-leg trousers",
    "Turtleneck sweater + Pleated wool skirt",
    "Basic tee + Skinny jeans accented with a denim jacket",
    "Halter sundress with a defined bodice and flared skirt",
    "Performance tee + Compression leggings",
    "Peplum top + High-waisted wrap skirt",
    "Velvet blouse + Wide-leg trousers",
    "Polo-style knit top + Slim chinos",
    "Fringe top + High-waisted flared pants",
    "Knit sweater + Skinny denim jeans",
    "Off-shoulder crop top + Paperbag waist shorts",
    "Tailored shirt dress with a cinched waist",
    "Tube top + Flared skater skirt",
    "Asymmetric blouse + Tailored culottes",
    "Wrap blouse + High-waisted trousers",
    "Retro halter top + A-line mini skirt",
    "Graphic tee + Cargo pants",
    "Lace blouse + Pleated midi skirt",
    "Statement knit top + Sleek leather pants",
    "Peasant blouse + Flowy maxi skirt",
    "Ruffled top + High-waisted pencil skirt",
    "Silk blouse + Wide-leg trousers",
    "Mesh top + Athletic shorts",
    "Peplum top + Denim mini skirt",
    "Light knit sweater + Jogger trousers",
    "Bodysuit + Tailored high-waisted trousers",
    # New swimwear and underwear outfits:
    "Bikini top + Matching low-rise bikini bottoms",
    "Chic one-piece swimsuit with a flattering silhouette",
    "Lace bralette + Cheeky briefs",
    "Cotton camisole + Coordinated high-waisted briefs"
]

full_body_dress_styles = [
    "Random",
    "None",
    "Crew-neck tee + Denim jeans + (White sneakers:1.5)",
    "Cropped top + Distressed shorts + (Strappy sandals:1.5)",
    "Structured blouse + Pencil skirt + (Low-heeled pumps:1.5)",
    "Button-up shirt + Tapered trousers + (Classic loafers:1.5)",
    "Off-shoulder blouse + Midi skirt + (Ankle strap heels:1.5)",
    "Tank top + Denim shorts + (Espadrille sandals:1.5)",
    "Mesh tank + Athletic leggings + (Running trainers:1.5)",
    "Sequin camisole + Slim trousers + (Stiletto heels:1.5)",
    "Ruffled blouse + Floral skirt + (Ballet flats:1.5)",
    "Lace top + Maxi skirt + (Flat sandals:1.5)",
    "Graphic tee + Mini skirt + (Combat boots:1.5)",
    "Off-shoulder crop top + Mini skirt + (Heeled ankle boots:1.5)",
    "Satin blouse + Straight-leg trousers + (Pointed-toe heels:1.5)",
    "Turtleneck sweater + Wool skirt + (Knee-high boots:1.5)",
    "Basic tee + Skinny jeans + Denim jacket + (Slip-on sneakers:1.5)",
    "Halter sundress + Flared skirt + (Wedge sandals:1.5)",
    "Performance tee + Compression leggings + (Athletic sneakers:1.5)",
    "Peplum top + Wrap skirt + (Kitten heels:1.5)",
    "Velvet blouse + Wide-leg trousers + (Heeled mules:1.5)",
    "Polo-style knit top + Slim chinos + (Classic loafers:1.5)",
    "Fringe top + Flared pants + (Platform sandals:1.5)",
    "Knit sweater + Denim jeans + (Ankle boots:1.5)",
    "Off-shoulder crop top + Paperbag shorts + (Strappy block heels:1.5)",
    "Shirt dress + Belt + (Classic pumps:1.5)",
    "Tube top + Skater skirt + (Espadrille wedges:1.5)",
    "Asymmetric blouse + Culottes + (Minimalist sandals:1.5)",
    "Wrap blouse + Trousers + (Heeled sandals:1.5)",
    "Retro halter top + Mini skirt + (Kitten heels:1.5)",
    "Graphic tee + Cargo pants + (Slip-on sneakers:1.5)",
    "Lace blouse + Midi skirt + (Pointed flats:1.5)",
    "Statement knit top + Leather pants + (Ankle boots:1.5)",
    "Peasant blouse + Maxi skirt + (Strappy sandals:1.5)",
    "Ruffled top + Pencil skirt + (Heeled pumps:1.5)",
    "Silk blouse + Wide-leg trousers + (Classic pumps:1.5)",
    "Mesh top + Athletic shorts + (Running sneakers:1.5)",
    "Peplum top + Denim mini skirt + (Comfortable flats:1.5)",
    "Light knit sweater + Joggers + (Casual slip-ons:1.5)",
    "Bodysuit + High-waisted trousers + (Stiletto heels:1.5)",
    # New swimwear and underwear outfits:
    "Bikini top + Matching bikini bottoms + (Flip-flops:1.5)",
    "Chic one-piece swimsuit + (Beach sandals:1.5)",
    "Lace bralette + Cheeky briefs + (Cozy house slippers:1.5)",
    "Cotton camisole + Coordinated high-waisted briefs + (Soft slip-ons:1.5)"
]





dress_styles2 = ["Random", "None"] + [
    "Shift Dress",
    "A-line Dress",
    "Maxi Dress",
    "Midi Dress",
    "Mini Dress",
    "Shirt Dress",
    "T-shirt Midi Dress",
    "Sweater Dress",
    "Printed Belted Shirt Dress",
    "Cotton Padded T-shirt Dress",
    "Smock Dress",
    "Short-sleeve Mini Dress",
    "Sleeveless Peplum Mini Dress",
    "Structured Mini Dress",
    "Sheath Dress",
    "Wrap Dress",
    "Bodycon Dress",
    "Fit and Flare Dress",
    "Empire Waist Dress",
    "Halter Neck Dress",
    "Off-the-shoulder Dress",
    "Strapless Dress",
    "High-low Dress",
    "Mermaid Dress",
    "Princess Dress",
    "Tiered Dress",
    "Corset Dress",
    "Flapper Dress",
    "Printed Chiffon Midi Dress",
    "Printed Chiffon Mini Dress",
    "3/4 Sleeve Crêpe Midi Dress",
    "Embroidered Bell Sleeve Mini Dress",
    "Printed Crêpe Midi Dress",
    "Kimono Dress",
    "Sundress",
    "Chemise Dress",
    "Slip Dress",
    "Corset and Garter Belt Set",
    "Babydoll and Chemise",
    "Crop Top and Mini Skirt",
    "Crop Top and Shorts",
    "Sleeveless Top Paired with Wide-leg Pants",
    "Button-down Shirt with Tailored Shorts",
    "Crop Top Paired with High-waisted Trousers",
    "T-shirt Paired with Bermuda Shorts",
    "Peasant Blouse with Jeans",
    "Tailored Blazer Paired with Trousers",
    "Button-up Shirt Tucked into High-waisted Pants",
    "Knit Sweater Layered over a Collared Shirt with Trousers",
    "Jacket Layered over a Tank Top with Jeans",
    "Cardigan Worn over a Camisole with Leggings",
    "Tunic Top Paired with Leggings or Jeggings",
    "Sweatshirt Paired with Joggers",
    "Hoodie Paired with Cargo Pants",
    "Blouse with a Pencil Skirt and a Belt",
    "Structured Suit Jacket with Matching Pants",
    "Jumpsuit",
    "Romper",
    "Palazzo Pants with Blouse",
    "Boiler Suit",
    "Athleisure Set (Leggings and Sports Bra)",
    "Tracksuit",
    "One-piece Swimsuit with Floral Print",
    "Cutout Monokini",
    "High-waisted Bikini with Ruffled Top",
    "Classic Triangle Bikini with String Ties",
    "Strapless Bandeau Bikini with Side-tie Bottoms",
    "Tankini",
    "Denim Jacket",
    "Trench Coat",
    "Puffer Jacket",
    "Peacoat"
]


dress_styles = [
    "Random",
    "None",
    "Knee length A-line Dress with a scoop neck and short sleeves",
    "Calf-length Midi Dress with a round neck and three-quarter sleeves",
    "Knee length Shirt Dress with a button-up collar and long sleeves",
    "Above-knee length Smock Dress with a square neck and puff sleeves",
    "Thigh-length Mini Dress with a V-neck and short sleeves",
    "Floor-length Evening Gown with a sweetheart neckline and sleeveless design",
    "Knee-length Bodycon Dress with a high neck and cap sleeves",
    "Midi-length Off-the-shoulder Dress with an off-shoulder neckline and ruffled sleeves",
    "Knee-length Summer Dress with a halter neck and sleeveless design",
    "Ankle-length Kimono Dress with a wrap V-neck and wide kimono sleeves",
    "Hip-length blazer with a notch lapel and long sleeves, paired with full-length trousers",
    "Full-length joggers and a zip-up jacket with a crew neck and long sleeves",
    "One-piece Swimsuit with Floral Print - Mid-thigh coverage with a scoop neck and adjustable spaghetti straps",
]

dress_colours = ["Random", "None"] + [
    "Crimson coloured",
    "Maroon coloured",
    "Red coloured",
    "Rose coloured",
    "Ruby coloured",
    "Scarlet coloured",
    "Coral coloured",
    "Orange coloured",
    "Peach coloured",
    "Salmon coloured",
    "Gold coloured",
    "Lemon coloured",
    "Mustard coloured",
    "Yellow coloured",
    "Forest green coloured",
    "Green coloured",
    "Mint coloured",
    "Olive coloured",
    "Teal coloured",
    "Emerald coloured",
    "Aqua coloured",
    "Blue coloured",
    "Indigo coloured",
    "Navy coloured",
    "Royal blue coloured",
    "Sky blue coloured",
    "Turquoise coloured",
    "Cyan coloured",
    "Lavender coloured",
    "Magenta coloured",
    "Orchid coloured",
    "Pink coloured",
    "Purple coloured",
    "Violet coloured",
    "Burgundy coloured",
    "Fuchsia coloured",
    "Lilac coloured",
    "Mauve coloured",
    "Periwinkle coloured",
    "Plum coloured",
    "Beige coloured",
    "Black coloured",
    "Brown coloured",
    "Charcoal coloured",
    "Chocolate coloured",
    "Gray coloured",
    "Ivory coloured",
    "Silver coloured",
    "Slate coloured",
    "Tan coloured",
    "White coloured",
    "Taupe coloured",
    "Khaki coloured"
]
dress_patterns_textures = ["Random", "None"] + [
    "* Fabric Types * Cotton",
    "* Fabric Types * Chiffon",
    "* Fabric Types * Denim",
    "* Fabric Types * Jersey",
    "* Fabric Types * Lace",
    "* Fabric Types * Leather",
    "* Fabric Types * Linen",
    "* Fabric Types * Mesh",
    "* Fabric Types * Polyester",
    "* Fabric Types * Rayon",
    "* Fabric Types * Satin",
    "* Fabric Types * Silk",
    "* Fabric Types * Tulle",
    "* Fabric Types * Velvet",
    "* Fabric Types * Faux Fur",
    "* Fabric Types * Organza",
    "* Prints and Patterns * Abstract",
    "* Prints and Patterns * Animal Print",
    "* Prints and Patterns * Checkered",
    "* Prints and Patterns * Floral",
    "* Prints and Patterns * Geometric",
    "* Prints and Patterns * Gingham",
    "* Prints and Patterns * Houndstooth",
    "* Prints and Patterns * Ombre",
    "* Prints and Patterns * Paisley",
    "* Prints and Patterns * Plaid",
    "* Prints and Patterns * Polka Dots",
    "* Prints and Patterns * Stripes",
    "* Prints and Patterns * Tie-dye",
    "* Prints and Patterns * Zebra Patterned",
    "* Prints and Patterns * Argyle",
    "* Textured and Embellished Fabrics * Brocade",
    "* Textured and Embellished Fabrics * Crochet",
    "* Textured and Embellished Fabrics * Embroidery",
    "* Textured and Embellished Fabrics * Fringe",
    "* Textured and Embellished Fabrics * Jacquard",
    "* Textured and Embellished Fabrics * Sequins",
    "* Textured and Embellished Fabrics * Smocked",
    "* Textured and Embellished Fabrics * Quilted",
    "* Textured and Embellished Fabrics * Ribbed",
    "* Textured and Embellished Fabrics * Matelassé",
    "* Textured and Embellished Fabrics * Cable Knit",
    "* Textured and Embellished Fabrics * Waffle Knit",
    "* Specialty and Historical Fabrics * Batik",
    "* Specialty and Historical Fabrics * Baroque",
    "* Specialty and Historical Fabrics * Damask",
    "* Specialty and Historical Fabrics * Dobby",
    "* Specialty and Historical Fabrics * Eyelet",
    "* Specialty and Historical Fabrics * Herringbone",
    "* Specialty and Historical Fabrics * Piqué",
    "* Specialty and Historical Fabrics * Swiss Dot",
    "* Specialty and Historical Fabrics * Tweed",
    "* Design and Construction Details * Ruffles",
    "* Design and Construction Details * Seamless",
    "* Design and Construction Details * Sheer",
    "* Design and Construction Details * Smocked",
    "* Design and Construction Details * Quilted",
    "* Design and Construction Details * Ribbed"
]

dress_materials = ["Random", "None"] + [
    "Cotton",
    "Chiffon",
    "Corduroy",
    "Denim",
    "Jersey",
    "Brushed Fleece",
    "Lace",
    "Leather",
    "Linen",
    "Mesh",
    "Polyester",
    "Rayon",
    "Satin",
    "Silk",
    "Tulle",
    "Velvet",
    "Viscose",
    "Faux Fur",
    "Wool",
    "Organza"
]

dress_patterns = ["Random", "None"] + [
    "Abstract",
    "Animal Print",
    "Checkered",
    "Floral",
    "Geometric",
    "Chevron",
    "Gingham",
    "Houndstooth",
    "Jacquard",
    "Paisley",
    "Plaid",
    "Polka Dots",
    "Stripes",
    "Tie-dye",
    "Brocade",
    "Embroidery",
    "Quilted"
]




color_textures = [
    "Random",
    "None",
    "Simple, Plain, Minimal details, Uniform background",
    "Sparse, Basic, Few details, Straightforward background",
    "Clean, Neat, Moderate details, Organized background",
    "Balanced, Orderly, Balanced details, Structured background",
    "Average, Decent, Standard details, Typical background",
    "Elaborate, Engaging, Abundant details, Engaging background",
    "Rich, Intricate, Detailed elements, Rich background",
    "Complex, Varied, Diverse details, Intricate background",
    "Exquisite, Ornate, Elaborate details, Ornate background",
    "Intricate, Detailed, Highly detailed scene, Intricate background"
]

depthfocus_list = [
    "Random",
    "None",
    "background blurred",
    "background slightly blurred",
    "background sharp",
    "softly focused background",
    "bokeh background"
]

moods = [
    "Random",
    "None",
    "Tranquil",
    "Vibrant",
    "Mysterious",
    "Melancholic",
    "Energetic",
    "Dreamy",
    "Chaotic",
    "Romantic",
    "Nostalgic",
    "Foreboding",
    "Joyful",
    "Anxious",
    "Hopeful",
    "Reflective"
]

lightings = ["Random", "None"] + [
    "* Night : Clear * Clear night with starry skies and moonlight",
    "* Night : Foggy * Foggy night with eerie moonlight",
    "* Night : Foggy * Foggy night with moonlit silhouettes",
    "* Day : Cloudy * Cloudy day with warm sunlight",
    "* Day : Cloudy * Cloudy day with warm sunlight reflecting off water",
    "* Day : Misty * Misty day with glowing light",
    "* Day : Misty * Misty day with glowing light during sunrise",
    "* Day : Overcast * Overcast day with dimmed sunlight",
    "* Day : Overcast * Overcast day with gentle diffused light",
    "* Day : Overcast * Overcast day with soft, ethereal light",
    "* Day : Overcast * Overcast day with foggy conditions",
    "* Day : Rainy * Rainy day with misty light",
    "* Day : Overcast * Overcast day with sleet",
    "* Day : Snowy * Snowy day with sparkling light on fresh snow",
    "* Day : Sunny * Sunny day with clear blue skies",
    "* Day : Sunny * Sunny day with soft sunlight",
    "* Day : Sunny * Sunny day with soft sunlight filtering through clouds",
    "* Day : Sunny * Sunny day with vibrant sunlight",
    "* Day : Sunny * Sunny day with warm golden light",
    "* Sunset/Sunrise : Clear * Sunrise with clear sky",
    "* Sunset/Sunrise : Sunny * Sunset with golden hour light",
    "* Sunset/Sunrise : Misty * Misty day with glowing light during sunrise"
]

adjectives = [
    "Random",
    "None",
    "Majestic",
    "Spectacular",
    "Breathtaking",
    "Picturesque",
    "Scenic",
    "Idyllic",
    "Untouched",
    "Pristine",
    "Lush",
    "Barren",
    "Mystical",
    "Rugged",
    "Enchanting",
    "Awe-inspiring",
    "Ethereal",
    "Vivid",
    "Charming",
    "Elegant"
]

landscapes = ["Random", "None"] + [
    "Mountains background",
    "Plateaus background",
    "Canyons background",
    "Cliffs background",
    "Volcanoes background",
    "Valleys background",
    "Plains background",
    "Deserts background",
    "Grasslands background",
    "Savannas background",
    "Taigas background",
    "Lakes background",
    "Rivers background",
    "Waterfalls background",
    "Oceans background",
    "Seas background",
    "Bays background",
    "Fjords background",
    "Coral reefs background",
    "Icebergs background",
    "Sand dunes background",
    "Forests background",
    "Rainforests background",
    "Tundras background",
    "Swamps background",
    "Marshes background",
    "Snow-covered forest background",
    "Tropical islands background",
    "Archipelagos background",
    "Desert oasis with palm trees background",
    "City skyline background",
    "Bridge background",
    "Highway interchange background",
    "Skyscraper background",
    "Apartment balcony with city views background",
    "Urban park background",
    "Botanical garden background",
    "Amusement park background",
    "Carousel in a fairground background",
    "Urban alley with graffiti background",
    "Street market background",
    "Fountain in a public square background",
    "Zoo background",
    "Rooftop garden background",
    "Residential neighborhood background",
    "Shopping mall background",
    "Office complex background",
    "Industrial area background",
    "Convention center background",
    "Seaport background",
    "Harbor background",
    "Historical landmark background",
    "Cemetery background",
    "Castle ruins background",
    "Medieval fortress background",
    "Dam background",
    "Canal background",
    "Aqueduct background",
    "Sports stadium background",
    "Hot air balloon basket background",
    "Ski resort background",
    "Horse stable background",
    "Rustic barn background",
    "Farm with rolling fields background",
    "Orchard in bloom background",
    "Vineyard with grapevines background",
    "Wildflower meadow background",
    "Sunset beach with dunes background",
    "Lavender field background",
    "Tulip field background",
    "Pumpkin patch background",
    "Theme park background",
    "Carousel in a fairground background",
    "Theater stage with velvet curtains background",
    "Recording studio with soundproofing background",
    "Dance studio with mirrored walls background",
    "Yoga studio with mats and meditation area background",
    "Bowling alley with polished lanes background",
    "Game room with a pool table background",
    "Craft room with sewing machine background",
    "Living room with a fireplace background",
    "Kitchen with a breakfast bar background",
    "Bedroom with a cozy bed background",
    "Home office with a desk and bookshelves background",
    "Bathroom with a bathtub background",
    "Dining room with a chandelier background",
    "Library with floor-to-ceiling shelves background",
    "Art studio with easels and paints background",
    "Music room with instruments background",
    "Gym with exercise equipment background",
    "Home theater with plush seating background",
    "Wine cellar with wine racks background",
    "Sunroom with indoor plants background",
    "Conservatory with a grand piano background",
    "Attic with vintage furniture background",
    "Basement lounge with a bar background",
    "Children's playroom with toys background",
    "Laundry room with washing machine background",
    "Mudroom with storage cubbies background",
    "Walk-in closet with shelves and mirrors background",
    "Pantry with shelves stocked with food background",
    "Garage with tools and workbench background",
    "Studio apartment with minimalist decor background",
    "Loft with exposed brick walls background",
    "Hotel lobby with luxurious furnishings background",
    "Hotel room with a king-size bed background",
    "Restaurant with elegant decor background",
    "Café with cozy seating background",
    "Bookstore with reading nooks background",
    "Art gallery with white walls and spotlights background",
    "Museum exhibit with artifacts background",
    "University lecture hall with rows of seats background",
    "Classroom with chalkboard and desks background",
    "Hospital room with medical equipment background",
    "Spa with massage tables and candles background",
    "Beauty salon with hair styling stations background",
    "Tattoo parlor with art-covered walls background",
    "Photography studio with backdrop and lights background",
    "Indoor pool with lounge chairs background",
    "Old library with antique books background",
    "Underwater in a swimming pool background"
]


# Image Crop Zoom lists
aspect_ratios = [
    "9:21 640x1536 (0.42)",
    "9:19 704x1472 (0.48)",
    "9:16 768x1344 (0.57)",
    "5:8 768x1216 (0.63)",
    "2:3 832x1216 (0.68)",
    "3:4 896x1152 (0.78)",
    "1:1 1024x1024 (1.00)",
    "4:3 1152x896 (1.29)",
    "3:2 1216x832 (1.46)",
    "8:5 1216x768 (1.58)",
    "16:9 1344x768 (1.75)",
    "19:9 1472x704 (2.09)",
    "21:9 1536x640 (2.40)",
    "unchanged"
]

oc_aspectratios = {
    "9:21 640x1536 (0.42)": (640, 1536),
    "9:19 704x1472 (0.48)": (704, 1472),
    "9:16 768x1344 (0.57)": (768, 1344),
    "5:8 768x1216 (0.63)": (768, 1216),
    "2:3 832x1216 (0.68)": (832, 1216),
    "3:4 896x1152 (0.78)": (896, 1152),
    "1:1 1024x1024 (1.00)": (1024, 1024),
    "4:3 1152x896 (1.29)": (1152, 896),
    "3:2 1216x832 (1.46)": (1216, 832),
    "8:5 1216x768 (1.58)": (1216, 768),
    "16:9 1344x768 (1.75)": (1344, 768),
    "19:9 1472x704 (2.09)": (1472, 704),
    "21:9 1536x640 (2.40)": (1536, 640),
    "unchanged": None
}